version: "3"
services:
 web:
   build: .
   ports:
     - "8080:8080"
   command:
    bash -c "cd my_site
    && python manage.py makemigrations
    && python manage.py migrate
    && python manage.py fill_db
    && python manage.py runserver"