version: "3"
services:
 web:
   build: .
   ports:
     - "8000:8000"
   command:
    bash -c "cd my_site
    && python manage.py makemigrations
    && python manage.py migrate
    && python manage.py fill_db
    && python manage.py runserver 0.0.0.0:8000"